services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=30
      - LOG_LEVEL=info
      - SELF_UPDATE=true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: ghcr.io/btambara/brian-tambara-com:main
    restart: unless-stopped
    ports:
      - "80:80"
