services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: ghcr.io/btambara/brian-tambara-com:main
    restart: always
    ports:
      - "80:80"
